[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib", "zlib"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -U pip",
  "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && /opt/venv/bin/python app.py"